### ISSUE TITLE
Torrent Server for Metadata

### ISSUE THREAD

**Issue by RekhaTcs** [Colored-Coins/coloredcoinsd#6]
I saw an API called addMetadata , which is expecting a token from torrent  server.
Can anyone help me in answering the following questions?

1) What is the token that they are referring to?
2) And in one of the colored coins documentation , I came across that Bittorrent protocol is used to store and share data.
 so my question is whether colored coins is restricted to Bittorent.

**Comment by oleiba** [comment]
Our Torrent server is currently a closed source and only allows private requests.
As such, it requires a JWT (JSON web token) encoded with a secret configured in both servers environment variables.
It uses [https://github.com/Colored-Coins/Metadata-Handler](url) as a Bittorrent client, to seed and download metadata torrents.
Regarding your second question - I am not sure I understand what you're asking, but anyway:
Yes, Colored-Coins protocol relies on the Bittorrent network, from the thought of being able to store assets metadata without size limits, and staying within the architecture of peer-to-peer.
The connection between a colored-coins transaction and its corresponding meta-data is achieved with the encoding of the torrent info-hash (20 bytes SHA1).
