### ISSUE TITLE
"Local" integration tests should not start a socket server or require manual testing

### ISSUE THREAD

**Issue by drauschenbach** [Colored-Coins/coloredcoinsd#9]
`supertest` provides the means to perform local integration testing of Express endpoints without starting a socket server, which is problematic on CI servers.

I refactored for this, and pulled `issueAssetV2` into the unit test suite, and it passes.

**Comment by oleiba** [comment]
Thanks for the feedback and the PR.
I have opened and merged PR #12  based on yours, including some fixtures to `issueAssetV2` since it was out of date.
